name: Deploy to Vercel
on:
  push:
    branches: [homepage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.kRLz9z2oiVfh9XFgjkGcCpQg }}
          vercel-org-id: ${{ secrets.team_IOYogd4DczGConNVZ9Hx94S4 }}
          vercel-project-id: ${{ secrets.prj_gS5CLNj1H7yQPBcDX4bcdXWy8PVM }}
          vercel-args: '--prod'
